name: bigpicture
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aiodns=3.5.0=py313h06a4308_1
  - aiohappyeyeballs=2.6.1=py313h06a4308_0
  - aiohttp=3.13.2=py313hee96239_0
  - aiosignal=1.4.0=py313h06a4308_0
  - anyio=4.10.0=py313h06a4308_0
  - anywidget=0.9.18=py313h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py313hee96239_0
  - asttokens=3.0.0=py313h06a4308_0
  - async-lru=2.0.5=py313h06a4308_0
  - attrs=25.4.0=py313h06a4308_2
  - babel=2.16.0=py313h06a4308_0
  - beautifulsoup4=4.13.5=py313h06a4308_0
  - blas=1.0=openblas
  - bleach=6.2.0=py313h06a4308_0
  - blosc=1.21.6=hef167b5_0
  - boto3=1.40.54=py313h06a4308_0
  - botocore=1.40.54=py313h06a4308_0
  - bottleneck=1.4.2=py313haa0f9ac_1
  - bqplot=0.12.45=pyhe01879c_0
  - branca=0.8.1=py313h06a4308_0
  - brotlicffi=1.1.0.0=py313hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=5.5.1=py313h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - cfitsio=4.2.0=hd9d235c_0
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.1.8=py313h06a4308_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colour=0.1.4=pyhd67b51d_0
  - comm=0.2.3=py313h06a4308_0
  - contourpy=1.3.3=py313hdb19cb5_0
  - cryptography=46.0.3=py313h0a354b3_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py313hbdd6827_1
  - decorator=5.2.1=py313h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - earthengine-api=1.7.1=pyhd8ed1ab_0
  - eerepr=0.1.2=pyhd8ed1ab_0
  - executing=2.2.1=py313h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=2.8.6=0
  - ffmpeg-python=0.2.0=pyhff2d567_1
  - filelock=3.20.0=py313h06a4308_0
  - folium=0.20.0=py313h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py313hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py313hbdd6827_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdown=5.2.0=pyhd8ed1ab_1
  - geeadd=0.5.6=pyhd8ed1ab_0
  - geemap=0.36.6=pyhd8ed1ab_0
  - geocoder=1.38.1=pyhd8ed1ab_2
  - geojson=3.2.0=pyhd8ed1ab_0
  - geos=3.12.0=h59595ed_0
  - geotiff=1.7.1=hf074850_14
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.1=hfc55251_0
  - glib-tools=2.78.1=hfc55251_0
  - google-api-core=2.26.0=py313h06a4308_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.38.0=py313h06a4308_1
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-cloud-core=2.5.0=py313h06a4308_0
  - google-cloud-storage=3.4.1=py313h06a4308_0
  - google-crc32c=1.6.0=py313h5eee18b_0
  - google-resumable-media=2.7.2=py313h06a4308_0
  - googleapis-common-protos=1.69.2=py313h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py313h06a4308_1
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - httpcore=1.0.9=py313h06a4308_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - httpx=0.28.1=py313h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - ipyevents=2.0.4=pyhbbac1ac_0
  - ipyfilechooser=0.6.0=pyhd8ed1ab_0
  - ipykernel=6.31.0=py313h7040dfc_0
  - ipyleaflet=0.19.2=py313h06a4308_0
  - ipython=9.7.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - ipytree=0.2.2=pyhd8ed1ab_1
  - ipywidgets=8.1.7=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - jmespath=1.0.1=py313h06a4308_0
  - json-c=0.17=h1220068_1
  - json5=0.9.25=py313h06a4308_0
  - jsonschema=4.25.0=py313h06a4308_1
  - jsonschema-specifications=2025.9.1=py313h06a4308_0
  - jupyter=1.1.1=py313h06a4308_0
  - jupyter-lsp=2.2.5=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_1
  - jupyter_console=6.6.3=py313h06a4308_1
  - jupyter_core=5.8.1=py313h06a4308_0
  - jupyter_events=0.12.0=py313h06a4308_0
  - jupyter_leaflet=0.19.2=h06a4308_0
  - jupyter_server=2.16.0=py313h06a4308_0
  - jupyter_server_terminals=0.5.3=py313h06a4308_0
  - jupyterlab=4.4.7=py313h06a4308_0
  - jupyterlab_pygments=0.3.0=py313h06a4308_0
  - jupyterlab_server=2.28.0=py313h06a4308_0
  - jupyterlab_widgets=3.0.15=py313h06a4308_0
  - kealib=1.5.3=hf8d3e68_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.83.1=h38339ff_5
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.7=hadbb8c3_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=1.1.1=h0131e85_1
  - libboost=1.88.0=h9d9b81f_0
  - libcrc32c=1.1.2=h6a678d5_0
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal=3.6.4=h4779e86_21
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkml=1.3.0=haa4a5bd_1022
  - libkrb5=1.21.3=h520c7b4_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libpq=16.10=h1cdf469_1
  - librttopo=1.1.0=hb58d41b_14
  - libsodium=1.0.20=heac8642_0
  - libspatialite=5.0.1=h090f1da_29
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - logzero=1.7.0=py313h78bf25f_7
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib-base=3.10.6=py313h4948728_1
  - matplotlib-inline=0.2.1=py313h06a4308_0
  - minizip=4.0.3=hf59b114_0
  - mistune=3.1.2=py313h06a4308_0
  - multidict=6.7.0=py313hee96239_0
  - narwhals=2.7.0=py313h06a4308_0
  - nbclient=0.10.2=py313h06a4308_0
  - nbconvert=7.16.6=py313h06a4308_0
  - nbconvert-core=7.16.6=py313h06a4308_0
  - nbconvert-pandoc=7.16.6=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - notebook=7.4.5=py313h06a4308_0
  - notebook-shim=0.2.4=py313h06a4308_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numexpr=2.14.1=py313ha5a4a6c_0
  - numpy=2.3.4=py313h816806e_1
  - numpy-base=2.3.4=py313h7203c5b_1
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=py313h06a4308_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py313h06a4308_0
  - parso=0.8.5=py313h06a4308_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.9.0=py313h06a4308_1
  - pillow=10.4.0=py313hc9074d1_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py313h06a4308_0
  - plotly=6.3.0=py313h7040dfc_0
  - poppler=23.08.0=habdc1e1_3
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.10=hd526058_1
  - proj=9.3.0=h1d62c97_2
  - prometheus_client=0.21.1=py313h06a4308_0
  - prompt-toolkit=3.0.52=py313h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py313h5eee18b_0
  - proto-plus=1.26.1=py313h06a4308_0
  - protobuf=5.29.3=py313h386a9ef_0
  - psutil=7.0.0=py313hee96239_1
  - psygnal=0.12.0=py313h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313h06a4308_0
  - pyasn1=0.6.1=py313h06a4308_0
  - pyasn1-modules=0.4.2=py313h06a4308_0
  - pycares=4.10.0=py313ha137689_0
  - pycparser=2.23=py313h06a4308_0
  - pycrs=1.0.2=pyhd8ed1ab_1
  - pygments=2.19.2=py313h06a4308_0
  - pyopenssl=25.3.0=py313hef88997_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyperclip=1.11.0=pyha804496_0
  - pyshp=3.0.2.post1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.0=h9ebbce0_101_cp313
  - python-box=7.3.2=py313h07c4f96_1
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-fastjsonschema=2.20.0=py313h06a4308_0
  - python-json-logger=3.2.1=py313h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.3=py313h591646f_0
  - pyzmq=27.1.0=py313hcf8288c_1
  - qhull=2020.2=h434a139_5
  - qtconsole=5.7.0=py313h06a4308_0
  - qtpy=2.4.3=py313h06a4308_0
  - rasterio=1.4.3=py313h720536b_0
  - ratelim=0.1.6=pyhd8ed1ab_3
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py313h06a4308_0
  - requests=2.32.5=py313h06a4308_1
  - rfc3339-validator=0.1.4=py313h06a4308_0
  - rfc3986-validator=0.1.1=py313h06a4308_0
  - rpds-py=0.28.0=py313h498d7c9_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.18.16=py313h4aee224_0
  - ruamel.yaml.clib=0.2.14=py313h4aee224_0
  - s3transfer=0.14.0=py313h06a4308_0
  - scooby=0.11.0=pyhd8ed1ab_0
  - send2trash=1.8.2=py313h06a4308_1
  - setuptools=80.9.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.0=py313h06a4308_0
  - soupsieve=2.5=py313h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py313h06a4308_0
  - terminado=0.18.1=py313h06a4308_0
  - tesseract=5.4.1=h485c14c_1
  - tiledb=2.16.3=hf0b6e87_3
  - tinycss2=1.4.0=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_1
  - traitlets=5.14.3=py313h06a4308_0
  - traittypes=0.2.3=py313h7040dfc_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h04d1e81_0
  - uriparser=0.9.8=hac33072_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=py313h06a4308_0
  - uvloop=0.22.1=py313h939ff40_1
  - wcwidth=0.2.13=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - websocket-client=1.8.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - widgetsnbextension=4.0.14=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - x264=1!164.3095=h166bdaf_2
  - xclip=0.13=hb9d3cd8_4
  - xerces-c=3.2.4=h6a678d5_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxmu=1.2.1=h9b100fa_1
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xsel=1.2.1=hb9d3cd8_6
  - xyzservices=2025.4.0=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py313hee96239_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/erik/.conda/envs/bigpicture
